In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import string

In [3]:
# Empty list for collect all the reviews
reviews = []

# Empty list to collect all the rating star
rating = []

# Empty list to collect all the dates
date = []

# Empty list to collect all the country names of the passengers
country = []

In [4]:
base_url = "https://www.airlinequality.com/airline-reviews/british-airways"

for i in range(1, 38):
    print(f"Scraping page {i}")

    # Create URL to collect links from paginated data
    url = f"{base_url}/page/{i}/?sortby=post_date%3ADesc&pagesize=100"

    # Collect HTML data from this page
    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'html.parser')
    
    #For reviews
    for item in soup.find_all("div", {"class": "text_content"}):
        reviews.append(item.text)
    
    # For ratings
    for item in soup.find_all("div", {"class": "rating-10"}):
        try:
            rating.append(item.span.text)
        except:
            print(f"Error found at page {i}")
            rating.append("None")
    
    # For date
    for item in soup.find_all("time"):
        date.append(item.text)
        
    # For country
    for item in soup.find_all("h3"):
        country.append(item.span.next_sibling.text.strip(" ()"))
    
    print(f"   ---> {len(reviews)} total reviews")

Scraping page 1
   ---> 100 total reviews
Scraping page 2
   ---> 200 total reviews
Scraping page 3
   ---> 300 total reviews
Scraping page 4
   ---> 400 total reviews
Scraping page 5
   ---> 500 total reviews
Scraping page 6
   ---> 600 total reviews
Scraping page 7
   ---> 700 total reviews
Scraping page 8
   ---> 800 total reviews
Scraping page 9
   ---> 900 total reviews
Scraping page 10
   ---> 1000 total reviews
Scraping page 11
   ---> 1100 total reviews
Scraping page 12
   ---> 1200 total reviews
Scraping page 13
   ---> 1300 total reviews
Scraping page 14
   ---> 1400 total reviews
Scraping page 15
   ---> 1500 total reviews
Scraping page 16
   ---> 1600 total reviews
Scraping page 17
   ---> 1700 total reviews
Scraping page 18
   ---> 1800 total reviews
Scraping page 19
   ---> 1900 total reviews
Scraping page 20
   ---> 2000 total reviews
Scraping page 21
   ---> 2100 total reviews
Scraping page 22
   ---> 2200 total reviews
Scraping page 23
   ---> 2300 total reviews
Scraping page 24
   ---> 2400 total reviews
Scraping page 25
   ---> 2500 total reviews
Scraping page 26
   ---> 2600 total reviews
Scraping page 27
   ---> 2700 total reviews
Scraping page 28
   ---> 2800 total reviews
Scraping page 29
   ---> 2900 total reviews
Scraping page 30
   ---> 3000 total reviews
Scraping page 31
   ---> 3100 total reviews
Scraping page 32
Error found at page 32
   ---> 3200 total reviews
Scraping page 33
Error found at page 33
   ---> 3300 total reviews
Scraping page 34
Error found at page 34
   ---> 3400 total reviews
Scraping page 35
   ---> 3500 total reviews
Scraping page 36
Error found at page 36
Error found at page 36
   ---> 3600 total reviews
Scraping page 37
   ---> 3700 total reviews

In [5]:
# len(reviews)
# len(country)
rating = rating[:3700]
# len(date)
# len(rating)

In [6]:
df = pd.DataFrame({"Reviews":reviews, "Rating":rating, "Date":date, "Country":country})
df

,Reviews,Rating,Date,Country
0,✅ Trip Verified | As always when I fly BA it ...,\n\t\t\t\t\t\t\t\t\t\t\t\t\t5,9th January 2024,Spain
1,✅ Trip Verified | First time using BA busines...,1,7th January 2024,United Kingdom
2,Not Verified | Extremely rude ground service....,9,3rd January 2024,United States
3,✅ Trip Verified | My son and I flew to Geneva...,6,2nd January 2024,China
4,✅ Trip Verified | For the price paid (bought ...,1,29th December 2023,United Kingdom
...,...,...,...,...
3695,Once again a good flight from LHR to Warsaw in...,10,11th May 2014,United Kingdom
3696,LGW-MRU-LGW in business. Outbound flight good ...,6,11th May 2014,United Kingdom
3697,LHR-FRA-LCY May 2014. LHR-FRA on a 767 row 18....,2,11th May 2014,United Kingdom
3698,Rating : 10/10 Cabin Flown Economy Value for M...,9,11th May 2014,United Kingdom
3699,08/5/2014 JFK-LHR-BRU. After the perfect outbo...,8,11th May 2014,Belgium

## Exporting the data set to csv

In [7]:
df.to_csv("BA_Scraped Data.csv")

In [8]:
df.shape

(3700, 4)